### ISSUE TITLE
Clarifications required Homework 3 (to be submitted by June 28)

### ISSUE THREAD

**Issue by anishcr** [ConsenSys/india-training#39]
1) Anyone can contribute ethers to the contract at any time.

2) This means the amount held in the contract can vary from time to time.

3) When someone submits a proprosal, he can submit value which is 10% of the value held by that contract at that time.

4) A proposal will be in Submitted state, Approved state, Rejected State,  Money Completely Withdrawn state or Money Partially Withdrawn state.
Can the beneficiary withdraw amounts (for the same proposal) at different times? ( The only requirement is that the sum of withdrawal has to be less than or equal to the approved amount).

5) A beneficiary can submit only one proposal at a time?
He can propose only after his previous proposals are in one of the following states - Rejected or Money Completely Withdrawn state?

6) Can an Approver keep changing his mind by calling Approve or Reject for a given beneficiary as many times as possible (if the proposal is in Submitted state)?

7) Since a beneficiary can withdraw at any time, there is a possibility that the contract does not have enough ether to transfer.
For eg, 20 proposals were submitted each for 10% of the contract value.
If all are approved, then there is not enough ethers to provide for all. Whoever withdraws first will receive the ether!!!

8) An "final" approve will fail if there is no sufficient ethers in the contract (for the submitted proposal value)
say there was no sufficient ether in contract when the first approver "approved", but it will be success.
but when the second approver "approve's" the contract, it will fail since there is no ether?

**Comment by danielnovy** [comment]
4) Yes
5) Only one at a time. A beneficiary cannot have two open proposals.
6) No. The votes are final.
7)"there is a possibility that the contract does not have enough ether to transfer."
I'm pretty sure you, my beloved students, won't allow that to happen, right? :)
8) The situation of not having enough Ether in the contract should never happen.

To simplify things, let's assume that there will be a contribution period after which no more contribution can be made. I will update the README file accordingly. Thanks for your excellent questions, @anishcr!

**Comment by anishcr** [comment]
Thank you for the reply @danielnovy 

1) So if there is going to be a contribution period, i assume that people can submit proposal only after contribution period is over. (also there is not going to be a "submission phase" after which approval/rejection starts?)

2) Since approval and withdrawal is dynamic, a user can submit for a value which is 10% of the current value of the contract (and not the total contributions).

3) I still see the possibility that the contract does not have enough ether to transfer because on approval, the ether is NOT transferred to the beneficiary. 

Option is to Approve a contract only if there is enough balance in the contract.
Say 100 ether's were contributed.
20 proposals submitted for 10 ether each.
let us say the first 10 proposals were approved (but the beneficiary did not withdraw).
Since there is no more ether left, the remaining 10 proposals cannot be approved.
The con's of this approach is that the beneficiary might not withdraw all the approved money, which could have been provided to someone else.

**Comment by anurag-git** [comment]
*   Its not very clear who will deploy the contract from the signers, and will it have any special privilege.
*   contribute function is not mentioned, hence I plan to create a new function named `contribute()`.
*   Bit confused on contract state mentioned in ` AbstractMultiSig.sol`  (i.e "Accepting contributions" and "Active" v/s proposal state mentioned by @anishcr (i.e Submitted state, Approved state, Rejected State, Money Completely Withdrawn state or Money Partially Withdrawn state.)
Questions:
- contract state and proposal state is same or different?
- Once first is clarified, please clearly mention the different state possible so that it's clear for everyone.

**Comment by anishcr** [comment]
One clarification about the endContributionPeriod()

1) Only the signer's can call this function.

2) If any one of the signers call the function, we change the state to Contribution Ended .
ie, there is no need of a majority vote on this function to end the contribution period.

**Comment by anishcr** [comment]
@anurag-git , this is my current understanding.

1) Contract can have two states - "Accepting Contributions" OR "Active" state.
In "Accepting Contributions" states, users can fund the contract. In this state, users CANNOT submit proposal, and signers CANNOT approve/reject proposal (obviously, since no proposal is submitted).

In "Active" state, users CANNOT fund the contract. in this state, users can submit proposal, and singers can approve/reject proposal.

2) The Submitted state, Approved state, Rejected State, Money Completely Withdrawn state or Money Partially Withdrawn states are what I visualized about the states of a proposal. It is my design and not something that is proposed by Daniel.

**Comment by anishcr** [comment]
@anurag-git 

Reg _"Its not very clear who will deploy the contract from the signers.txt, and will it have any special privilege."_

The signers.txt will have the address's of the persons who can approve or reject the submitted proposals. They are the *only* ones who are "voting"!

Reg _"contribute function is not mentioned, hence I plan to create a new function named contribute."_

Anyone can contribute to the fund. This is just transfer of ethers/weis to the fund. The fund transfer does not need a function.

**Comment by danielnovy** [comment]
Thanks for your answers to Anurag, Anish. You are right in all of them. 

About the problem of the contract not having enough Ethers, this should be avoided. I just want you guys to use the common sense here. If someone submitted a proposal, the value asked should not be available anymore! You will only make this value available again if the proposal is refused. Until then, the value asked should be blocked.

**Comment by anishcr** [comment]
Daniel, while submitting a proposal, the value has to be available and locking the value to that submission (and releasing if it is rejected) makes life easier. Thanks!

I was thinking of having a "Submission Phase" after "Contribution Phase", so that users can submit as many proposals as possible. You made my (our!) life simpler by above suggestion. Thanks again.
