### ISSUE TITLE
endContributorPeriod() Admin

### ISSUE THREAD

**Issue by sarangparikh22** [ConsenSys/india-training#41]
The endContributorPeriod() function should be ideally called by the Contract Creator/Owner or else anybody can end the proposal period. But if we add that, there will be a problem in checking the contract for the Test Cases because then only we(Contract Owner) can call it and Daniel won't be able to check for other conditions.

So , do we have to make endContributorPeriod() call by Owner only or anybody can call it.
PS: In real life scenario, we shouldn't allow anybody to call this but only Owner.

**Comment by sarangparikh22** [comment]
Thanks Daniel for consideration. 
I have one more doubt, Can same beneficiary have multiple proposals?
Eg: One address can request say 10 ethers can the same address request 20 ethers more. If yes, should both the request be merged, added as new proposal or the original amount gets replaced with the new amount that is requested.

**Comment by anishcr** [comment]
If only the owner can call the endContribution period, Daniel will not be able to test contract's deployed by us. 

i was thinking the following.

1) Only the signer's can call the endContribution function.

2) If any one of the signers call the function, we change the state to Contribution Ended .
ie, there is no need of a majority vote on this function to end the contribution period.

**Comment by mishra1010** [comment]
The above endcontribution can be avoided if we set a minimum contribution limit and a signer has to do a minimum contribution to enter the proposal and to have the ability to vote if signer satisfies the minimum contribution criteria.
Also we are not sure how many times a signer can contribute

**Comment by danielnovy** [comment]
Mishra, signers do not contribute! They are just signers of the contract. 

Anish, I like your suggestion. Only signers can call the “endContribution” function. I will update the readme accordingly.

**Comment by mishra1010** [comment]
Thanks Daniel, i understand now.
signers cannot contribute. The statement "Anyone can feed the contract with Ethers" in readme created the confusion

**Comment by anishcr** [comment]
Daniel, Amit, 
My understanding is that signer's or for that matter anyone (including users who submit proposal) can contribute to the contract. Let me know if this is not correct.

Only the signers can vote (approve/reject) a submitted proposal. The majority of the signers (only) will decide the fate of a submitted proposal (ie, whether it is accepted or rejected).

**Comment by moinuddin14** [comment]
Daniel only mentioned as signers do not contribute but not cannot contribute. So the statement “Anyone can feed the contract with Ethers” still hold true.

**Comment by sarangparikh22** [comment]
Anyone can send ethers to the contract, but only signer has the capability to end the contribution period. The contributors have no say in the signing process and the signing process is done only by the signers.
@moinuddin14

**Comment by anishcr** [comment]
@moinuddin14 , maybe https://github.com/ConsenSys/india-training/issues/44 will help clarify

**Comment by danielnovy** [comment]
@mishra1010 I have to apologize. Definitely, signers can contribute, yes. But this doesn't change anything in the dynamics of the contract. Important thing to realize here is that contributing or not does not determine if a given address is a signer or not. The signers are specified in the `signers.txt` file.

@anishcr Your statement `My understanding is that signer's or for that matter anyone (including users who submit proposal) can contribute to the contract.` => You are correct.
