### ISSUE TITLE
HomeWork 3 - Ether vs Wei

### ISSUE THREAD

**Issue by anishcr** [ConsenSys/india-training#43]
In the AbstractMultiSig.sol, value parameter in the Functions and also Events are mentioned as "Ethers".

Just wanted to double check that this is Ethers only and not Wei.

Also a user can contribute to the fund any value (including less than an ether) in Wei.

Wei and Ether support will mean we need to do conversion in code as needed. So wanted to be sure before i write the extra code. (The easiest will be if you allow everything to be specified in Wei :)!)

**Comment by anishcr** [comment]
Just to add. If we need to support only in "ether", then the value in the ReceivedContribution Event will be in Wei only. Please correct me if I am wrong.

**Comment by danielnovy** [comment]
Anish, once more thank you for the comment. You are right, let’s make everything in Wei to simplify things :)

I will update the readme (once again).

**Comment by anishcr** [comment]
Thanks Daniel.
